### ISSUE TITLE
Add intern profiles to website

### ISSUE THREAD

**Issue by MaxGhenis** [UBICenter/ubi-center#103]
The [internship](https://www.ubicenter.org/about/internship) is receiving applications through June 19. One intern (Nate Golden) has already confirmed they'll start on June 22. Add Nate and other confirmed interns to the About page together.

**Comment by MaxGhenis** [comment]
Done. cc @ngpsu22 it's official! http://ubicenter.org/about

**Comment by ngpsu22** [comment]
Looks great!


Sent from Yahoo Mail for iPhone


On Thursday, June 25, 2020, 9:22 PM, Max Ghenis <notifications@github.com> wrote:




Closed #103.
