### ISSUE TITLE
Clarify whether the Freedom Dividend stacks with housing assistance

### ISSUE THREAD

**Issue by MaxGhenis** [UBICenter/ubi-center#83]
In March, 2018, Andrew Yang [tweeted]( https://twitter.com/AndrewYang/status/970104619832659968):
>Medicare and housing left alone.
That is, the Freedom Dividend would stack on housing benefits.

On 2019-08-17, a Twitter user [tweeted](https://twitter.com/HvEvil/status/1162913710647730181):
>I got some clarification on benefits that stack with the #FreedomDividend by asking AndrewYang today. Sadly, it won't stack with housing benefits.

I've emailed Yang's team and will update accordingly. 

For now, I'll leave the analysis as-is (with housing assistance stacking) since the sole statement from Yang himself says it stacks.

**Comment by MaxGhenis** [comment]
[Tweet](https://twitter.com/scottsantens/status/1185996907669348354) today from (informal?) Yang adviser Scott Santens says:
>I've spoken to Yang about this. Housing stacks. The details will be released in a full housing plan that will be released soon, although I don't know exactly when. Expect a detailed plan for housing like we have seen for democracy reform, climate change, and veteran assistance.

**Comment by sillvva** [comment]
He mentions directly that it stacks with housing: https://youtu.be/GZv5mDHT3IE?t=3351

**Comment by MaxGhenis** [comment]
Thank you, @sillvva. In this town hall from 2019-10-11, Yang says:
>It stacks on top of housing assistance because many of the people have been waiting literally years and years and they're trying to get affordable housing and then the affordable housing would consume the Freedom Dividend.

This in addition to Scott's tweet is good enough for me to close and leave the analysis as-is, with housing assistance stacking.
